### ISSUE TITLE
Permissão de Acesso

### ISSUE THREAD

**Issue by jonasvpereira** [a2c/bacon-manager#2]
Criar configurador de permissões por usuário e ação. As permissões devem seguir a hierarquia de permissão por pessoa e por grupo. Caso o usuário não tenha permissão de executar alguma atividade não deve aparecer o botão ou link.

**Comment by adanfm** [comment]
Foi implementado somente permissão por grupo, criado extensões do Twig para fazer as tratativas das ações que o usuário tem ou não permissão.
